// Copyright (c) 2014 Dataence, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sequence

import (
	"testing"

	"github.com/stretchr/testify/require"
)

var (
	sigtests = []struct {
		msg, sig string
	}{
		{"jan 12 06:49:41 irc sshd[7034]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=218-161-81-238.hinet-ip.hinet.net  user=root", "%time%[%integer%]:(:):;==%integer%=%integer%===="},
		{"jan 12 06:49:42 irc sshd[7034]: failed password for root from 218.161.81.238 port 4228 ssh2", "%time%[%integer%]:%ipv4%%integer%"},
		{"9.26.157.45 - - [16/jan/2003:21:22:59 -0500] \"get /wssamples/ http/1.1\" 200 1576", "%ipv4%--[%time%]\"\"%integer%%integer%"},
		{"209.36.88.3 - - [03/may/2004:01:19:07 +0000] \"get http://npkclzicp.xihudohtd.ngm.au/abramson/eiyscmeqix.ac;jsessionid=b0l0v000u0?sid=00000000&sy=afr&kw=goldman&pb=fin&dt=selectrange&dr=0month&so=relevance&st=nw&ss=afr&sf=article&rc=00&clspage=0&docid=fin0000000r0jl000d00 http/1.0\" 200 27981", "%ipv4%--[%time%]\"%url%\"%integer%%integer%"},
		{"4/5/2012 17:55,172.23.1.101,1101,172.23.0.10,139, generic protocol command decode,3, [1:2100538:17] gpl netbios smb ipc$ unicode share access ,tcp ttl:128 tos:0x0 id:1643 iplen:20 dgmlen:122 df,***ap*** seq: 0xcef93f32  ack: 0xc40c0bb  n: 0xfc9c  tcplen: 20,", "%time%,%ipv4%,%integer%,%ipv4%,%integer%,,%integer%,[%integer%:%integer%:%integer%],:%integer%::%integer%:%integer%:%integer%,::n::%integer%,"},
		{"2012-04-05 17:54:47     local4.info     172.23.0.1      %asa-6-302015: built outbound udp connection 1315679 for outside:193.0.14.129/53 (193.0.14.129/53) to inside:172.23.0.10/64048 (10.32.0.1/52130)", "%time%%ipv4%:%integer%:%ipv4%/%integer%(%ipv4%/%integer%):%ipv4%/%integer%(%ipv4%/%integer%)"},
		{"may  2 19:00:02 dlfssrv sendmail[18980]: taa18980: from user daemon: size is 596, class is 0, priority is 30596, and nrcpts=1, message id is <200305021400.taa18980@dlfssrv.in.ibm.com>, relay=daemon@localhost", "%time%[%integer%]:::%integer%,%integer%,%integer%,=%integer%,<>,="},
		{"jan 12 06:49:56 irc last message repeated 6 times", "%time%%integer%"},
		{"9.26.157.44 - - [16/jan/2003:21:22:59 -0500] \"get http://wssamples http/1.1\" 301 315", "%ipv4%--[%time%]\"%url%\"%integer%%integer%"},
		{"2012-04-05 17:51:26     local4.info     172.23.0.1      %asa-6-302016: teardown udp connection 1315632 for inside:172.23.0.2/514 to identity:172.23.0.1/514 duration 0:09:23 bytes 7999", "%time%%ipv4%:%integer%:%ipv4%/%integer%:%ipv4%/%integer%%integer%:%integer%:%integer%%integer%"},
		{"id=firewall time=\"2005-03-18 14:01:43\" fw=topsec priv=4 recorder=kernel type=conn policy=504 proto=tcp rule=deny src=210.82.121.91 sport=4958 dst=61.229.37.85 dport=23124 smac=00:0b:5f:b2:1d:80 dmac=00:04:c1:8b:d8:82", "==\"%time%\"==%integer%===%integer%===%ipv4%=%integer%=%ipv4%=%integer%=%mac%=%mac%"},
		{"mar 01 09:42:03.875 pffbisvr smtp[2424]: 334 warning: denied access to command 'ehlo vishwakstg1.msn.vishwak.net' from [209.235.210.30]", "%time%[%integer%]:%integer%:''[%ipv4%]"},
		{"mar 01 09:45:02.596 pffbisvr smtp[2424]: 121 statistics: duration=181.14 user=<egreetings@vishwak.com> id=zduqd sent=1440 rcvd=356 srcif=d45f49a2-b30 src=209.235.210.30/61663 cldst=192.216.179.206/25 svsrc=172.17.74.195/8423 dstif=fd3c875c-064 dst=172.17.74.52/25 op=\"to 1 recips\" arg=<vishwakstg1ojte15fo000033b4@vishwakstg1.msn.vishwak.net> result=\"250 m2004030109385301402 message accepted for delivery\" proto=smtp rule=131 (denied access to command 'ehlo vishwakstg1.msn.vishwak.net' from [209.235.210.30])", "%time%[%integer%]:%integer%:=%float%=<>==%integer%=%integer%==%ipv4%/%integer%=%ipv4%/%integer%=%ipv4%/%integer%==%ipv4%/%integer%=\"\"=<>=\"\"==%integer%(''[%ipv4%])"},
	}

	seqtests = []struct {
		msg string
		seq Sequence
	}{
		{
			"Jan 12 06:49:41 irc sshd[7034]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=218-161-81-238.hinet-ip.hinet.net  user=root", Sequence{
				Token{TokenTime, FieldUnknown, "Jan 12 06:49:41"},
				Token{TokenLiteral, FieldUnknown, "irc"},
				Token{TokenLiteral, FieldUnknown, "sshd"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "7034"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "pam_unix"},
				Token{TokenLiteral, FieldUnknown, "("},
				Token{TokenLiteral, FieldUnknown, "sshd"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "auth"},
				Token{TokenLiteral, FieldUnknown, ")"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "authentication"},
				Token{TokenLiteral, FieldUnknown, "failure"},
				Token{TokenLiteral, FieldUnknown, ";"},
				Token{TokenLiteral, FieldUnknown, "logname"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "uid"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "0"},
				Token{TokenLiteral, FieldUnknown, "euid"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "0"},
				Token{TokenLiteral, FieldUnknown, "tty"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "ssh"},
				Token{TokenLiteral, FieldUnknown, "ruser"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "rhost"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "218-161-81-238.hinet-ip.hinet.net"},
				Token{TokenLiteral, FieldUnknown, "user"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "root"},
			},
		},

		{
			"Jan 12 06:49:42 irc sshd[7034]: Failed password for root from 218.161.81.238 port 4228 ssh2", Sequence{
				Token{TokenTime, FieldUnknown, "Jan 12 06:49:42"},
				Token{TokenLiteral, FieldUnknown, "irc"},
				Token{TokenLiteral, FieldUnknown, "sshd"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "7034"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "Failed"},
				Token{TokenLiteral, FieldUnknown, "password"},
				Token{TokenLiteral, FieldUnknown, "for"},
				Token{TokenLiteral, FieldUnknown, "root"},
				Token{TokenLiteral, FieldUnknown, "from"},
				Token{TokenIPv4, FieldUnknown, "218.161.81.238"},
				Token{TokenLiteral, FieldUnknown, "port"},
				Token{TokenInteger, FieldUnknown, "4228"},
				Token{TokenLiteral, FieldUnknown, "ssh2"},
			},
		},

		//"Jan 13 17:25:59 jlz sshd[19322]: Accepted password for jlz from 108.61.8.124 port 56731 ssh2",
		//"Jan 12 14:44:48 irc sshd[11084]: Accepted publickey for jlz from 76.21.0.16 port 36609 ssh2",
		{
			"Jan 12 06:49:56 irc last message repeated 6 times", Sequence{
				Token{TokenTime, FieldUnknown, "Jan 12 06:49:56"},
				Token{TokenLiteral, FieldUnknown, "irc"},
				Token{TokenLiteral, FieldUnknown, "last"},
				Token{TokenLiteral, FieldUnknown, "message"},
				Token{TokenLiteral, FieldUnknown, "repeated"},
				Token{TokenInteger, FieldUnknown, "6"},
				Token{TokenLiteral, FieldUnknown, "times"},
			},
		},

		{
			"9.26.157.44 - - [16/Jan/2003:21:22:59 -0500] \"GET http://WSsamples HTTP/1.1\" 301 315", Sequence{
				Token{TokenIPv4, FieldUnknown, "9.26.157.44"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenTime, FieldUnknown, "16/Jan/2003:21:22:59 -0500"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "GET"},
				Token{TokenURL, FieldUnknown, "http://WSsamples"},
				Token{TokenLiteral, FieldUnknown, "HTTP/1.1"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenInteger, FieldUnknown, "301"},
				Token{TokenInteger, FieldUnknown, "315"},
			},
		},

		{
			"9.26.157.45 - - [16/Jan/2003:21:22:59 -0500] \"GET /WSsamples/ HTTP/1.1\" 200 1576", Sequence{
				Token{TokenIPv4, FieldUnknown, "9.26.157.45"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenTime, FieldUnknown, "16/Jan/2003:21:22:59 -0500"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "GET"},
				Token{TokenLiteral, FieldUnknown, "/WSsamples/"},
				Token{TokenLiteral, FieldUnknown, "HTTP/1.1"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenInteger, FieldUnknown, "200"},
				Token{TokenInteger, FieldUnknown, "1576"},
			},
		},

		{
			"209.36.88.3 - - [03/May/2004:01:19:07 +0000] \"GET http://npkclzicp.xihudohtd.ngm.au/abramson/eiyscmeqix.ac;jsessionid=b0l0v000u0?sid=00000000&sy=afr&kw=goldman&pb=fin&dt=selectRange&dr=0month&so=relevance&st=nw&ss=AFR&sf=article&rc=00&clsPage=0&docID=FIN0000000R0JL000D00 HTTP/1.0\" 200 27981", Sequence{
				Token{TokenIPv4, FieldUnknown, "209.36.88.3"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "-"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenTime, FieldUnknown, "03/May/2004:01:19:07 +0000"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "GET"},
				Token{TokenURL, FieldUnknown, "http://npkclzicp.xihudohtd.ngm.au/abramson/eiyscmeqix.ac;jsessionid=b0l0v000u0?sid=00000000&sy=afr&kw=goldman&pb=fin&dt=selectRange&dr=0month&so=relevance&st=nw&ss=AFR&sf=article&rc=00&clsPage=0&docID=FIN0000000R0JL000D00"},
				Token{TokenLiteral, FieldUnknown, "HTTP/1.0"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenInteger, FieldUnknown, "200"},
				Token{TokenInteger, FieldUnknown, "27981"},
			},
		},

		{
			"4/5/2012 17:55,172.23.1.101,1101,172.23.0.10,139, Generic Protocol Command Decode,3, [1:2100538:17] GPL NETBIOS SMB IPC$ unicode share access ,TCP TTL:128 TOS:0x0 ID:1643 IpLen:20 DgmLen:122 DF,***AP*** Seq: 0xCEF93F32  Ack: 0xC40C0BB  n: 0xFC9C  TcpLen: 20,", Sequence{
				Token{TokenTime, FieldUnknown, "4/5/2012 17:55"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenIPv4, FieldUnknown, "172.23.1.101"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenInteger, FieldUnknown, "1101"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenIPv4, FieldUnknown, "172.23.0.10"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenInteger, FieldUnknown, "139"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "Generic"},
				Token{TokenLiteral, FieldUnknown, "Protocol"},
				Token{TokenLiteral, FieldUnknown, "Command"},
				Token{TokenLiteral, FieldUnknown, "Decode"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenInteger, FieldUnknown, "3"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "1"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "2100538"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "17"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, "GPL"},
				Token{TokenLiteral, FieldUnknown, "NETBIOS"},
				Token{TokenLiteral, FieldUnknown, "SMB"},
				Token{TokenLiteral, FieldUnknown, "IPC$"},
				Token{TokenLiteral, FieldUnknown, "unicode"},
				Token{TokenLiteral, FieldUnknown, "share"},
				Token{TokenLiteral, FieldUnknown, "access"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "TCP"},
				Token{TokenLiteral, FieldUnknown, "TTL"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "128"},
				Token{TokenLiteral, FieldUnknown, "TOS"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "0x0"},
				Token{TokenLiteral, FieldUnknown, "ID"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "1643"},
				Token{TokenLiteral, FieldUnknown, "IpLen"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "20"},
				Token{TokenLiteral, FieldUnknown, "DgmLen"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "122"},
				Token{TokenLiteral, FieldUnknown, "DF"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "***AP***"},
				Token{TokenLiteral, FieldUnknown, "Seq"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "0xCEF93F32"},
				Token{TokenLiteral, FieldUnknown, "Ack"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "0xC40C0BB"},
				Token{TokenLiteral, FieldUnknown, "n"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "0xFC9C"},
				Token{TokenLiteral, FieldUnknown, "TcpLen"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "20"},
				Token{TokenLiteral, FieldUnknown, ","},
			},
		},

		{
			"2012-04-05 17:51:26     Local4.Info     172.23.0.1      %ASA-6-302016: Teardown UDP connection 1315632 for inside:172.23.0.2/514 to identity:172.23.0.1/514 duration 0:09:23 bytes 7999", Sequence{
				Token{TokenTime, FieldUnknown, "2012-04-05 17:51:26"},
				Token{TokenLiteral, FieldUnknown, "Local4.Info"},
				Token{TokenIPv4, FieldUnknown, "172.23.0.1"},
				Token{TokenLiteral, FieldUnknown, "%ASA-6-302016"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "Teardown"},
				Token{TokenLiteral, FieldUnknown, "UDP"},
				Token{TokenLiteral, FieldUnknown, "connection"},
				Token{TokenInteger, FieldUnknown, "1315632"},
				Token{TokenLiteral, FieldUnknown, "for"},
				Token{TokenLiteral, FieldUnknown, "inside"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenIPv4, FieldUnknown, "172.23.0.2"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "514"},
				Token{TokenLiteral, FieldUnknown, "to"},
				Token{TokenLiteral, FieldUnknown, "identity"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenIPv4, FieldUnknown, "172.23.0.1"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "514"},
				Token{TokenLiteral, FieldUnknown, "duration"},
				Token{TokenInteger, FieldUnknown, "0"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "09"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "23"},
				Token{TokenLiteral, FieldUnknown, "bytes"},
				Token{TokenInteger, FieldUnknown, "7999"},
			},
		},

		{
			"2012-04-05 17:54:47     Local4.Info     172.23.0.1      %ASA-6-302015: Built outbound UDP connection 1315679 for outside:193.0.14.129/53 (193.0.14.129/53) to inside:172.23.0.10/64048 (10.32.0.1/52130)", Sequence{
				Token{TokenTime, FieldUnknown, "2012-04-05 17:54:47"},
				Token{TokenLiteral, FieldUnknown, "Local4.Info"},
				Token{TokenIPv4, FieldUnknown, "172.23.0.1"},
				Token{TokenLiteral, FieldUnknown, "%ASA-6-302015"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "Built"},
				Token{TokenLiteral, FieldUnknown, "outbound"},
				Token{TokenLiteral, FieldUnknown, "UDP"},
				Token{TokenLiteral, FieldUnknown, "connection"},
				Token{TokenInteger, FieldUnknown, "1315679"},
				Token{TokenLiteral, FieldUnknown, "for"},
				Token{TokenLiteral, FieldUnknown, "outside"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenIPv4, FieldUnknown, "193.0.14.129"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "53"},
				Token{TokenLiteral, FieldUnknown, "("},
				Token{TokenIPv4, FieldUnknown, "193.0.14.129"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "53"},
				Token{TokenLiteral, FieldUnknown, ")"},
				Token{TokenLiteral, FieldUnknown, "to"},
				Token{TokenLiteral, FieldUnknown, "inside"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenIPv4, FieldUnknown, "172.23.0.10"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "64048"},
				Token{TokenLiteral, FieldUnknown, "("},
				Token{TokenIPv4, FieldUnknown, "10.32.0.1"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "52130"},
				Token{TokenLiteral, FieldUnknown, ")"},
			},
		},

		{
			"id=firewall time=\"2005-03-18 14:01:43\" fw=TOPSEC priv=4 recorder=kernel type=conn policy=504 proto=TCP rule=deny src=210.82.121.91 sport=4958 dst=61.229.37.85 dport=23124 smac=00:0b:5f:b2:1d:80 dmac=00:04:c1:8b:d8:82", Sequence{
				Token{TokenLiteral, FieldUnknown, "id"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "firewall"},
				Token{TokenLiteral, FieldUnknown, "time"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenTime, FieldUnknown, "2005-03-18 14:01:43"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "fw"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "TOPSEC"},
				Token{TokenLiteral, FieldUnknown, "priv"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "4"},
				Token{TokenLiteral, FieldUnknown, "recorder"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "kernel"},
				Token{TokenLiteral, FieldUnknown, "type"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "conn"},
				Token{TokenLiteral, FieldUnknown, "policy"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "504"},
				Token{TokenLiteral, FieldUnknown, "proto"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "TCP"},
				Token{TokenLiteral, FieldUnknown, "rule"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "deny"},
				Token{TokenLiteral, FieldUnknown, "src"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "210.82.121.91"},
				Token{TokenLiteral, FieldUnknown, "sport"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "4958"},
				Token{TokenLiteral, FieldUnknown, "dst"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "61.229.37.85"},
				Token{TokenLiteral, FieldUnknown, "dport"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "23124"},
				Token{TokenLiteral, FieldUnknown, "smac"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenMac, FieldUnknown, "00:0b:5f:b2:1d:80"},
				Token{TokenLiteral, FieldUnknown, "dmac"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenMac, FieldUnknown, "00:04:c1:8b:d8:82"},
			},
		},

		{
			"mar 01 09:42:03.875 pffbisvr smtp[2424]: 334 warning: denied access to command 'ehlo vishwakstg1.msn.vishwak.net' from [209.235.210.30]", Sequence{
				Token{TokenTime, FieldUnknown, "mar 01 09:42:03.875"},
				Token{TokenLiteral, FieldUnknown, "pffbisvr"},
				Token{TokenLiteral, FieldUnknown, "smtp"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "2424"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "334"},
				Token{TokenLiteral, FieldUnknown, "warning"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "denied"},
				Token{TokenLiteral, FieldUnknown, "access"},
				Token{TokenLiteral, FieldUnknown, "to"},
				Token{TokenLiteral, FieldUnknown, "command"},
				Token{TokenLiteral, FieldUnknown, "'"},
				Token{TokenLiteral, FieldUnknown, "ehlo vishwakstg1.msn.vishwak.net"},
				Token{TokenLiteral, FieldUnknown, "'"},
				Token{TokenLiteral, FieldUnknown, "from"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenIPv4, FieldUnknown, "209.235.210.30"},
				Token{TokenLiteral, FieldUnknown, "]"},
			},
		},

		{
			"may  2 19:00:02 dlfssrv sendmail[18980]: taa18980: from user daemon: size is 596, class is 0, priority is 30596, and nrcpts=1, message id is <200305021400.taa18980@dlfssrv.in.ibm.com>, relay=daemon@localhost", Sequence{
				Token{TokenTime, FieldUnknown, "may  2 19:00:02"},
				Token{TokenLiteral, FieldUnknown, "dlfssrv"},
				Token{TokenLiteral, FieldUnknown, "sendmail"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "18980"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "taa18980"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "from"},
				Token{TokenLiteral, FieldUnknown, "user"},
				Token{TokenLiteral, FieldUnknown, "daemon"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "size"},
				Token{TokenLiteral, FieldUnknown, "is"},
				Token{TokenInteger, FieldUnknown, "596"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "class"},
				Token{TokenLiteral, FieldUnknown, "is"},
				Token{TokenInteger, FieldUnknown, "0"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "priority"},
				Token{TokenLiteral, FieldUnknown, "is"},
				Token{TokenInteger, FieldUnknown, "30596"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "and"},
				Token{TokenLiteral, FieldUnknown, "nrcpts"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "1"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "message"},
				Token{TokenLiteral, FieldUnknown, "id"},
				Token{TokenLiteral, FieldUnknown, "is"},
				Token{TokenLiteral, FieldUnknown, "<"},
				Token{TokenLiteral, FieldUnknown, "200305021400.taa18980@dlfssrv.in.ibm.com"},
				Token{TokenLiteral, FieldUnknown, ">"},
				Token{TokenLiteral, FieldUnknown, ","},
				Token{TokenLiteral, FieldUnknown, "relay"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "daemon@localhost"},
			},
		},

		{
			"mar 01 09:45:02.596 pffbisvr smtp[2424]: 121 statistics: duration=181.14 user=<egreetings@vishwak.com> id=zduqd sent=1440 rcvd=356 srcif=d45f49a2-b30 src=209.235.210.30/61663 cldst=192.216.179.206/25 svsrc=172.17.74.195/8423 dstif=fd3c875c-064 dst=172.17.74.52/25 op=\"to 1 recips\" arg=<vishwakstg1ojte15fo000033b4@vishwakstg1.msn.vishwak.net> result=\"250 m2004030109385301402 message accepted for delivery\" proto=smtp rule=131 (denied access to command 'ehlo vishwakstg1.msn.vishwak.net' from [209.235.210.30])", Sequence{
				Token{TokenTime, FieldUnknown, "mar 01 09:45:02.596"},
				Token{TokenLiteral, FieldUnknown, "pffbisvr"},
				Token{TokenLiteral, FieldUnknown, "smtp"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenInteger, FieldUnknown, "2424"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenInteger, FieldUnknown, "121"},
				Token{TokenLiteral, FieldUnknown, "statistics"},
				Token{TokenLiteral, FieldUnknown, ":"},
				Token{TokenLiteral, FieldUnknown, "duration"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenFloat, FieldUnknown, "181.14"},
				Token{TokenLiteral, FieldUnknown, "user"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "<"},
				Token{TokenLiteral, FieldUnknown, "egreetings@vishwak.com"},
				Token{TokenLiteral, FieldUnknown, ">"},
				Token{TokenLiteral, FieldUnknown, "id"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "zduqd"},
				Token{TokenLiteral, FieldUnknown, "sent"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "1440"},
				Token{TokenLiteral, FieldUnknown, "rcvd"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "356"},
				Token{TokenLiteral, FieldUnknown, "srcif"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "d45f49a2-b30"},
				Token{TokenLiteral, FieldUnknown, "src"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "209.235.210.30"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "61663"},
				Token{TokenLiteral, FieldUnknown, "cldst"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "192.216.179.206"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "25"},
				Token{TokenLiteral, FieldUnknown, "svsrc"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "172.17.74.195"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "8423"},
				Token{TokenLiteral, FieldUnknown, "dstif"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "fd3c875c-064"},
				Token{TokenLiteral, FieldUnknown, "dst"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenIPv4, FieldUnknown, "172.17.74.52"},
				Token{TokenLiteral, FieldUnknown, "/"},
				Token{TokenInteger, FieldUnknown, "25"},
				Token{TokenLiteral, FieldUnknown, "op"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "to 1 recips"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "arg"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "<"},
				Token{TokenLiteral, FieldUnknown, "vishwakstg1ojte15fo000033b4@vishwakstg1.msn.vishwak.net"},
				Token{TokenLiteral, FieldUnknown, ">"},
				Token{TokenLiteral, FieldUnknown, "result"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "250 m2004030109385301402 message accepted for delivery"},
				Token{TokenLiteral, FieldUnknown, "\""},
				Token{TokenLiteral, FieldUnknown, "proto"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenLiteral, FieldUnknown, "smtp"},
				Token{TokenLiteral, FieldUnknown, "rule"},
				Token{TokenLiteral, FieldUnknown, "="},
				Token{TokenInteger, FieldUnknown, "131"},
				Token{TokenLiteral, FieldUnknown, "("},
				Token{TokenLiteral, FieldUnknown, "denied"},
				Token{TokenLiteral, FieldUnknown, "access"},
				Token{TokenLiteral, FieldUnknown, "to"},
				Token{TokenLiteral, FieldUnknown, "command"},
				Token{TokenLiteral, FieldUnknown, "'"},
				Token{TokenLiteral, FieldUnknown, "ehlo vishwakstg1.msn.vishwak.net"},
				Token{TokenLiteral, FieldUnknown, "'"},
				Token{TokenLiteral, FieldUnknown, "from"},
				Token{TokenLiteral, FieldUnknown, "["},
				Token{TokenIPv4, FieldUnknown, "209.235.210.30"},
				Token{TokenLiteral, FieldUnknown, "]"},
				Token{TokenLiteral, FieldUnknown, ")"},
			},
		},

		// {
		// 	"%msgtime% %apphost% %appname% : %srcuser% : tty = %string% ; pwd = %string% ; user = %dstuser% ; command = %method/10%", Sequence{
		// 		Token{TokenTime, FieldMsgTime, "%msgtime%"},
		// 		Token{TokenLiteral, FieldAppHost, "%apphost%"},
		// 		Token{TokenLiteral, FieldAppName, "%appname%"},
		// 		Token{TokenLiteral, FieldUnknown, ":"},
		// 		Token{TokenLiteral, FieldSrcUser, "%srcuser%"},
		// 		Token{TokenLiteral, FieldUnknown, ":"},
		// 		Token{TokenLiteral, FieldUnknown, "tty"},
		// 		Token{TokenLiteral, FieldUnknown, "="},
		// 		Token{TokenLiteral, FieldUnknown, "%string%"},
		// 		Token{TokenLiteral, FieldUnknown, ";"},
		// 		Token{TokenLiteral, FieldUnknown, "pwd"},
		// 		Token{TokenLiteral, FieldUnknown, "="},
		// 		Token{TokenLiteral, FieldUnknown, "%string%"},
		// 		Token{TokenLiteral, FieldUnknown, ";"},
		// 		Token{TokenLiteral, FieldUnknown, "user"},
		// 		Token{TokenLiteral, FieldUnknown, "="},
		// 		Token{TokenLiteral, FieldDstUser, "%dstuser%"},
		// 		Token{TokenLiteral, FieldUnknown, ";"},
		// 		Token{TokenLiteral, FieldUnknown, "command"},
		// 		Token{TokenLiteral, FieldUnknown, "="},
		// 		Token{TokenLiteral, FieldMethod, "%method/10%"},
		// 	},
		// },
	}
)

func TestMessageSignature(t *testing.T) {
	msg := &Message{}

	for _, tc := range sigtests {
		//msg.SetData(tc.msg)
		seq, err := msg.Tokenize(tc.msg)
		require.NoError(t, err)
		require.Equal(t, tc.sig, seq.Signature(), tc.msg+"\n"+seq.LongString())
	}
}

func TestMessageTokenize(t *testing.T) {
	msg := &Message{}

	for _, tc := range seqtests {
		//		msg.SetData(tc.msg)

		seq, err := msg.Tokenize(tc.msg)
		require.NoError(t, err)
		require.Equal(t, tc.seq, seq)
	}
}

func BenchmarkMessageOne(b *testing.B) {
	msg := &Message{}

	for i := 0; i < b.N; i++ {
		//msg.SetData(sigtests[0].msg)
		msg.Tokenize(sigtests[0].msg)
	}
}
